name: Update Places & Events, then Deploy

on:
  schedule:
    - cron: "0 16 * * *"  # Runs daily at 12:00 AM SGT (16:00 UTC previous day)
  workflow_dispatch:

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install requests python-dotenv

      # ===== Update Places =====
      - name: Generate places.json
        run: python get_places.py
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: Commit & Push places.json
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add public/data/places.json
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update places.json"
          fi

      # ===== Update Events =====
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node dependencies
        run: npm ci

      - name: Generate events.json
        run: node get_events.js
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}

      - name: Commit & Push events.json
        run: |
          git add public/data/events.json
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update events.json"
            git pull --rebase origin main
            git push origin main
          fi

      # ===== Deploy to Firebase =====
      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Firebase Deploy
        run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}