name: Update Places, Events, and Deploy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *" # Runs every day at midnight SGT (UTC+8)

jobs:
  update-places:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run get_places.py
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: python get_places.py

      - name: Commit & Push Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add public/data/places.json
          git commit -m "Auto-update places.json" || echo "No changes to commit"
          git push

  update-events:
    runs-on: ubuntu-latest
    needs: update-places
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run get_events.py
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: python get_events.py

      - name: Commit & Push Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add public/data/events.json
          git commit -m "Auto-update events.json" || echo "No changes to commit"
          git push

  firebase-deploy:
    runs-on: ubuntu-latest
    needs: [update-places, update-events]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting
