name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main     # run when you push to main
  schedule:
    - cron: "30 2 * * *"  # Runs daily at 10:30 AM SGT
  workflow_dispatch:       # allow manual trigger via GitHub UI

jobs:
  deploy:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        # Replace PROJECT_ID with your real Firebase project ID
        run: firebase deploy --project amara-concierge-88c12 --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
