name: Update Places Daily

on:
  push:
    branches:
      - main     # run when you push to main
  schedule:
    - cron: "30 2 * * *"  # Runs daily at 10:30 AM SGT
  workflow_dispatch:       # allow manual trigger via GitHub UI
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Generate places.json
        run: python get_places.py
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: Commit & Push changes (if any)
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add public/data/places.json
          if ! git diff --quiet; then
            git commit -m "Auto-update places.json"
            git pull --rebase origin main
            git push origin main
          else
            echo "✅ No changes to commit"
          fi