name: Update Events from SerpAPI

on:
  schedule:
    - cron: "30 2 * * *"  # Every day at 10:30am SGT
  workflow_dispatch:

jobs:
  scrape-events:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Run SerpAPI event fetcher
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: python get_serpapi_events.py

      - name: Commit and push if changed
        run: |
          if [[ -n "$(git status --porcelain events.json)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add events.json
            git commit -m "chore: update events.json from SerpAPI"
            git push
          else
            echo "No changes to commit."
